//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kongre_Online_Mini.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uye()
        {
            this.Aday = new HashSet<Aday>();
            this.AdayOy = new HashSet<AdayOy>();
            this.AdayYorum = new HashSet<AdayYorum>();
            this.Teklif = new HashSet<Teklif>();
            this.TeklifOy = new HashSet<TeklifOy>();
            this.TeklifYorum = new HashSet<TeklifYorum>();
        }
    
        public System.Guid UyeId { get; set; }
        public int MahalId { get; set; }
        public string isim { get; set; }
        public string Soyisim { get; set; }
        public string TelefonMobil { get; set; }
        public string TelefonSabit { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public int ilId { get; set; }
        public int UlkeId { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string DogumYeri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aday> Aday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdayOy> AdayOy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdayYorum> AdayYorum { get; set; }
        public virtual il il { get; set; }
        public virtual Mahal Mahal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teklif> Teklif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifOy> TeklifOy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifYorum> TeklifYorum { get; set; }
        public virtual Ulke Ulke { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
